delay: P14D
participants:
  - email: rbudinsk@redhat.com
    projects:
      - project: NON_EXISTING
        components: [Logging]
        maxIssues: 5
  - email: mstefank@redhat.com
    projects:
      - project: WFLY
        maxIssues: 10
      - project: WFCORE
        maxIssues: 10
      - project: JBTM
        maxIssues: 10

