delay: P14D
participants:
  - email: pberan@redhat.com
    projects:
      - project: WFLY
        maxIssues: 10
      - project: WFCORE
        maxIssues: 10
  - email: khermano@redhat.com
    projects:
      - project: WFLY
        maxIssues: 10
      - project: WFCORE
        maxIssues: 10
  - email: mjusko@redhat.com
    projects:
      - project: WFLY
        maxIssues: 10
      - project: WFCORE
        maxIssues: 10

